footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]

controller_frequency: 10.0
controller_patience: 15.0
clearing_radius: 0.59
footprint_padding: 0.015
shutdown_costmaps: true
